# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

variables:
  buildConfiguration: 'Release'
  ASPNETCORE_URLS: 'https://+:5001;http://+:5000'

pool:
  name: 'Maple-PC'
  vmImage: 'ubuntu-latest'

steps:
# Build
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'
    projects: '**/*.csproj'

# Test
- task: DotNetCoreCLI@2
  displayName: Testing
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

# Run the Web API in the background
- task: CmdLine@2
  displayName: Run the WebApi
  inputs:
    script: 'nohop dotnet $(Build.SourcesDirectory)/HotelBooking.WebApi/bin/$(buildConfiguration)/HotelBooking.WebApi.dll &'

# Install Newman
- task: Npm@1
  displayName: Install Newman
  inputs:
    command: 'custom'
    customCommand: 'install newman -g'

# Run Postman tests
- task: CmdLine@2
  displayName: Run Postman tests
  inputs:
    script: 'newman run $(Build.SourcesDirectory)/Postman/HotelBooking.postman_collection.json -k -r cli'